// ResumeAI by Priyanshu Mishra
// Complete Script: AI Resume + Trial + Payment + PDF

function generateResume() {
  const name = document.getElementById('name').value || 'Your Name';
  const email = document.getElementById('email').value || 'your@email.com';
  const phone = document.getElementById('phone').value || '+91 9876543210';
  const education = document.getElementById('education').value || 'Your education details';
  const skills = document.getElementById('skills').value || 'Your professional skills';
  const experience = document.getElementById('experience').value || 'Your work experience';

  document.getElementById('resumePreview').innerHTML = `
    <div style="font-family:Arial,sans-serif;color:#111827;padding:20px;">
      <h1 style="font-size:34px;margin-bottom:6px;">${name}</h1>
      <p style="color:#374151;">${email} | ${phone}</p>

      <hr style="margin:20px 0;border:1px solid #e5e7eb;">

      <h2 style="color:#2563eb;font-size:20px;">Professional Summary</h2>
      <p>Motivated and career-focused professional with strong technical knowledge and communication skills.</p>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Education</h2>
      <p>${education}</p>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Skills</h2>
      <p>${skills}</p>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Experience</h2>
      <p>${experience}</p>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Languages</h2>
      <p>English, Hindi</p>
    </div>
  `;
}

function generateAIResume() {
  const name = document.getElementById('name').value || 'Your Name';
  const email = document.getElementById('email').value || 'your@email.com';
  const phone = document.getElementById('phone').value || '+91 9876543210';
  const education = document.getElementById('education').value || 'Your education details';
  const skills = document.getElementById('skills').value || 'Communication, Problem Solving, Teamwork';
  const experience = document.getElementById('experience').value || 'Academic projects and internship experience';

  const aiSummary = `${name} is a highly motivated and career-oriented professional with a strong academic background in ${education}. Demonstrates expertise in ${skills} and possesses excellent analytical, communication, and teamwork abilities. Passionate about continuous learning and committed to delivering high-quality results in a professional environment.`;

  document.getElementById('resumePreview').innerHTML = `
    <div style="font-family:Arial,sans-serif;color:#111827;padding:20px;">

      <div style="display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #2563eb;padding-bottom:15px;margin-bottom:20px;">
        <div>
          <h1 style="font-size:34px;margin:0;">${name}</h1>
          <p style="color:#64748b;">${email} | ${phone}</p>
        </div>
        <div style="background:#2563eb;color:white;padding:8px 12px;border-radius:8px;font-size:12px;font-weight:600;">
          ATS READY
        </div>
      </div>

      <h2 style="color:#2563eb;font-size:20px;">Professional Summary</h2>
      <p style="line-height:1.8;">${aiSummary}</p>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Education</h2>
      <p style="line-height:1.8;">${education}</p>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Core Skills</h2>
      <ul style="padding-left:18px;line-height:1.8;">
        <li>${skills}</li>
        <li>Leadership & Team Collaboration</li>
        <li>Analytical Thinking</li>
        <li>Professional Communication</li>
      </ul>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Experience</h2>
      <p style="line-height:1.8;">${experience}</p>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Projects</h2>
      <ul style="padding-left:18px;line-height:1.8;">
        <li>AI Resume Builder</li>
        <li>Professional Portfolio Website</li>
        <li>Responsive Web Application</li>
      </ul>

      <h2 style="color:#2563eb;font-size:20px;margin-top:18px;">Languages</h2>
      <p>English, Hindi</p>

      <div style="margin-top:25px;padding-top:15px;border-top:1px solid #e5e7eb;color:#64748b;font-size:13px;">
        Generated by Priyanshu AI Resume Assistant
      </div>

    </div>
  `;
}

// 10-Day Free Trial System
function isTrialActive() {
  const trialStart = localStorage.getItem('resumeai_trial_start');

  if (!trialStart) {
    localStorage.setItem('resumeai_trial_start', new Date().toISOString());
    return true;
  }

  const startDate = new Date(trialStart);
  const currentDate = new Date();

  const diffTime = currentDate - startDate;
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));

  return diffDays < 10;
}

function getRemainingDays() {
  const trialStart = localStorage.getItem('resumeai_trial_start');

  if (!trialStart) return 10;

  const startDate = new Date(trialStart);
  const currentDate = new Date();

  const diffTime = currentDate - startDate;
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));

  return Math.max(0, 10 - diffDays);
}

// PDF Download + Payment Lock
function downloadPDF() {
    const element = document.getElementById("resumePreview");

    if (!element) {
        alert("Resume Preview nahi mila!");
        return;
    }

    if (!element.innerHTML.trim()) {
        alert("Pehle Generate Resume par click karo!");
        return;
    }

    const options = {
        margin: 0.4,
        filename: "ResumeAI_Professional_Resume.pdf",
        image: {
            type: "jpeg",
            quality: 0.98
        },
        html2canvas: {
            scale: 2,
            useCORS: true,
            backgroundColor: "#ffffff"
        },
        jsPDF: {
            unit: "in",
            format: "a4",
            orientation: "portrait"
        }
    };

    element.style.background = "#ffffff";
    element.style.color = "#111827";

    html2pdf()
        .set(options)
        .from(element)
        .save();
}

  const element = document.getElementById('resumePreview');

  const options = {
    margin: 0.5,
    filename: 'ResumeAI_Professional_Resume.pdf',
    image: {
      type: 'jpeg',
      quality: 1
    },
    html2canvas: {
      scale: 2,
      useCORS: true
    },
    jsPDF: {
      unit: 'in',
      format: 'a4',
      orientation: 'portrait'
    }
  };

  html2pdf().set(options).from(element).save();

}

// Update trial banner
document.addEventListener('DOMContentLoaded', function () {

  const remaining = getRemainingDays();

  const banner = document.getElementById('trialBanner');

  if (banner) {

    if (remaining > 0) {
      banner.innerHTML = `🎉 Free Trial: ${remaining} days remaining`;
    } else {
      banner.innerHTML = '⚠️ Free trial expired - ₹20 per resume';
    }

  }

});

// Reset payment
function resetPayment() {
  localStorage.removeItem('resumeai_paid');
}
/* ===== RESUME TEMPLATE SWITCHER ===== */

let selectedTemplate = "executive";

function selectTemplate(template, button) {
    selectedTemplate = template;

    // Remove active state from all template cards
    document.querySelectorAll(".template-card").forEach(card => {
        card.classList.remove("active");
    });

    // Add active state to selected card
    if (button) {
        button.classList.add("active");
    }

    // Apply selected template to resume preview
    const preview = document.getElementById("resumePreview");

    if (preview) {
        preview.classList.remove(
            "template-executive",
            "template-ats",
            "template-minimal",
            "template-creative",
            "template-corporate",
            "template-fresher"
        );

        preview.classList.add("template-" + template);
    }

    // Remember selected template
    localStorage.setItem("resumeai_selected_template", template);
}

/* Restore previously selected template */
document.addEventListener("DOMContentLoaded", function () {
    const savedTemplate =
        localStorage.getItem("resumeai_selected_template") || "executive";

    selectedTemplate = savedTemplate;

    const preview = document.getElementById("resumePreview");

    if (preview) {
        preview.classList.add("template-" + savedTemplate);
    }

    const selectedButton = document.querySelector(
        `.template-card[onclick*="'${savedTemplate}'"]`
    );

    if (selectedButton) {
        document.querySelectorAll(".template-card").forEach(card => {
            card.classList.remove("active");
        });

        selectedButton.classList.add("active");
    }
});
/* ===== SIMPLE 6 TEMPLATE SWITCHER ===== */

function selectTemplate(template, button) {

    const preview = document.getElementById("resumePreview");

    if (!preview) {
        alert("Resume preview nahi mila!");
        return;
    }

    preview.classList.remove(
        "template-executive",
        "template-ats",
        "template-minimal",
        "template-creative",
        "template-corporate",
        "template-fresher"
    );

    preview.classList.add("template-" + template);

    document.querySelectorAll(".template-card").forEach(function(card) {
        card.classList.remove("active");
    });

    if (button) {
        button.classList.add("active");
    }

    localStorage.setItem(
        "resumeai_selected_template",
        template
    );
}
